ALTER TABLE orders
    ADD COLUMN current_lat DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN current_lon DOUBLE PRECISION NOT NULL DEFAULT 0;

ALTER TABLE couriers
    ADD COLUMN current_lat DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN current_lon DOUBLE PRECISION NOT NULL DEFAULT 0;